### ISSUE TITLE
QUESTION: How do you transform Debian into Mint?

### ISSUE THREAD

**Issue by jhsu802701** [linuxmint/ubiquity#17]
This issue isn't a bug or a request for features or other changes.  I decided to ask the question here, as a Google search of "debootstrap" pointed me here.

Exactly what process do you use to transform the Debian Linux ISO into the LMDE ISO?  What automated script do you run that starts off with Debian Linux and produces the LMDE ISO in the end?  From what I've read and from my past experience in remastering LMDE (using MintConstructor) and antiX Linux, I'm guessing that your process involves creating a Linux distro using the debootstrap command to create your own special directory and download minimal Debian, chrooting into this directory, installing packages on top of this local Debian system, creating a special ISO directory (that includes all of the files that appear when one opens the ISO file), updating the file in the ISO directory that corresponds to the main system, and finally transforming the contents of the ISO directory into an ISO file.

**Comment by monsta** [comment]
> This issue isn't a bug or a request for features or other changes.

Then it shouldn't be here at all.

Please ask Clem via IRC: #linuxmint-dev at irc.spotchat.org
