### ISSUE TITLE
Ubiquity 2.18.8 hangs

### ISSUE THREAD

**Issue by juston-li** [linuxmint/ubiquity#22]
Due to a recent python3.4 update (3.4.0-2 -> 3.4.3-1) ubiquity2.18.8 hangs indefinitely.
The issue was reported on Ubuntu here: https://bugs.launchpad.net/ubuntu/+source/ubiquity/+bug/1326707

The issue was fixed upstream in 2.18.9, https://launchpadlibrarian.net/212954680/ubiquity_2.18.8.8_2.18.8.9.diff.gz (first diff)

**Comment by clefebvre** [comment]
Thanks

**Comment by clefebvre** [comment]
https://github.com/linuxmint/ubiquity/commit/7948f525ddb62c19b025da90260b5780817b8730
