### ISSUE TITLE
Some parts untraslated in Italian version

### ISSUE THREAD

**Issue by fcole90** [linuxmint/ubiquity#3]
Up to LM14 ubiquity has always had a bug. It showed the instructions in Italian, but when it's installing and a presentation is shown there is an alternating of pages in English and in Italian. When I mean alternating I want to say that page 1 is in Italian, page 2 in English, page 3 in Italian again, and the same after. Is this related to a bug in ubiquity or are there untranslated parts? If it's the latter I propose myself for translating.

**Comment by monsta** [comment]
https://translations.launchpad.net/ubuntu/+source/ubiquity
