### ISSUE TITLE
[Feature Req] Update outdated Firefox screenshot in the slideshow

### ISSUE THREAD

**Issue by mrworldwide1** [linuxmint/ubiquity#74]
The image in installer slide show should be updated, because for 3 years now Firefox redesigned its interface - pictures below. This is important to ensure Mint doesn't seem outdated, especially to new users who open up Firefox after installing the OS and see the inconsistency.

https://blog.mozilla.org/en/products/firefox/fresh-new-look-for-firefox/

**Current:**
![Screenshot from 2024-03-29 18-11-55](https://github.com/linuxmint/ubiquity/assets/66652566/ee91b0e2-4590-4159-bbac-56d087bcce5a)

**Expected:**
![image](https://github.com/linuxmint/ubiquity/assets/66652566/62e17b24-7790-4a60-9b47-6d827a7b6904)

**Comment by clefebvre** [comment]
Updated for Mint 22.
