### ISSUE TITLE
[feature request] Detect if /home is present in any of the partitions. if so give a "repair/ replace" option

### ISSUE THREAD

**Issue by solomoncyj** [linuxmint/ubiquity#85]
The option will wipe everything else and install Linux mint and will skip account creation steps. this helps in system recovery and allows users from other distro top try out Linux mint

**Comment by mtwebster** [comment]
You would still need to define a user - usernames and passwords don't live in the user's home folder.  If a user is knowledgeable enough to set up a separate home partition, then the 'Something else...' option during installation should be easy enough to navigate.

I also wouldn't recommend sharing a home directory between distributions. There often subtle and not so subtle differences in default home files, and different versions of apps, which could end up breaking configurations or preventing them being used (firefox profiles aren't backwards-compatible, for example).
